name: showcase-autotest
run-name: run-pipelines
on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: "Dryrun (do not submit pipeline to Tower"
        default: false
        type: boolean
        required: false

  schedule:
    # Every day at 2am
    - cron: "0 2 * * 1"

jobs:
  getdate:
    runs-on: ubuntu-latest
    steps:
      - name: "Get current date"
        run: |
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        id: date
    outputs:
      date: ${{ steps.date.outputs.date }}

  runtest:
    runs-on: ubuntu-latest
    name: ${{ matrix.pipeline.name }}.${{ matrix.compute_env.name }}
    needs: getdate
    continue-on-error: true
    outputs:
      runname: ${{ steps.id.outputs.name }}
      workspace: ${{ steps.id.outputs.workspace }}
    strategy:
      matrix:
        pipeline:
          - { name: hello, url: hello, rev: master, latest: true, profiles: "" }
        compute_env:
          - {
              name: aws,
              ref: seqera_aws_ireland_fusionv2_nvme,
              workdir: "s3://seqeralabs-showcase",
              workspace_id: "138659136604200",
            }
          - {
              name: azure,
              ref: seqera_azure_virginia,
              workdir: "az://seqeralabs-showcase",
              workspace_id: "138659136604200",
            }

    steps:
      - name: "export run name"
        run: |
          echo "name=${{ matrix.pipeline.name }}_${{ matrix.compute_env.name }}_${{ needs.getdate.outputs.date }}" >> $GITHUB_OUTPUT
          echo "workspace=${{ matrix.compute_env.workspace_id }}" >> $GITHUB_OUTPUT
        id: id

      - uses: seqeralabs/action-tower-launch@8ff078c8133a8ad2145a96752688a990198d6529
        if: ${{ !inputs.dryrun }}
        with:
          pipeline: ${{ matrix.pipeline.url }}
          workspace_id: ${{ steps.id.outputs.workspace }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ matrix.compute_env.ref }}
          workdir: "${{ matrix.compute_env.workdir }}/work/${{ matrix.pipeline.name }}/work-${{ needs.getdate.outputs.date }}"
          run_name: "${{ steps.id.outputs.name }}"
          revision: "${{ matrix.pipeline.rev }}"
          profiles: ${{ matrix.pipeline.profiles }}
          wait: SUBMITTED
          parameters: |
            {
                "outdir": "${{ matrix.compute_env.workdir }}/${{ matrix.pipeline.name }}/results-test-${{ needs.getdate.outputs.date }}",
                "hook_url": "${{ secrets.SLACK_HOOK_URL }}"
            }

      - name: "store run name"
        if: success()
        run: |
          echo '{ "name": "${{ steps.id.outputs.name }}", "workspace": "${{ steps.id.outputs.workspace }}" }' >> ${{ steps.id.outputs.name }}_${{ steps.id.outputs.workspace }}_${{ needs.getdate.outputs.date }}.json

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: ${{ needs.getdate.outputs.date }}_run_details
          path: "${{ steps.id.outputs.name }}_${{ steps.id.outputs.workspace }}_${{ needs.getdate.outputs.date }}.json"

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: ${{ matrix.pipeline.name }}_${{ matrix.compute_env.name }}_log
          path: tower_action_*.log

  checkmatrix:
    runs-on: ubuntu-latest
    needs: [runtest, getdate]
    continue-on-error: true
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.getdate.outputs.date }}_run_details
          path: run_details

      - name: "Echo run name after 2 mins"
        run: |
          ls -lh run_details
          cat run_details/*
          echo "matrix=$(cat run_details/* | jq -c --slurp .)" >> $GITHUB_OUTPUT
        id: matrix

  checkrun:
    runs-on: ubuntu-latest
    needs: [checkmatrix]
    continue-on-error: true
    environment: delay
    env:
      TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
      TOWER_WORKSPACE_ID: ${{ needs.runtest.outputs.workspace }}
    strategy:
      matrix:
        includes: ${{ fromJSON(needs.checkmatrix.outputs.matrix) }}

    steps:
      - name: "print names"
        run: |
          echo "${{ matrix }}"

      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.getdate.outputs.date }}_run_details
          path: run_details

      - name: "Echo run name after 2 mins"
        run: |
          ls -lh run_details
          cat run_details/*
          cat run_details/* | jq -c --slurp .

      - name: Install tw CLI
        run: |
          wget -L https://github.com/seqeralabs/tower-cli/releases/download/v0.7.3/tw-0.7.3-linux-x86_64
          mv tw-* tw
          chmod +x tw
          sudo mv tw /usr/local/bin/

      - name:
        if: ${{ !inputs.dryrun }}
        run: |
          export ID=$(tw -o json runs list --workspace ${{ needs.runtest.outputs.workspace }} --filter ${{ needs.runtest.outputs.runname }} | jq -r '.workflows[].workflow.id')
          echo "Run ID: $ID"
          tw -o json runs view -w ${{ needs.runtest.outputs.workspace }} -i $ID
