name: Continuous tests for running the pipelines on cloud
run-name: Submit workflow for periodic testing
on: 
    workflow_dispatch:
    schedule:
    # Every Monday at 2am
    - cron: '0 2 * * 1'


jobs:
    getdate:
        runs-on: ubuntu-latest
        steps:
            - name: "Get current date"
              run: |
                echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
              id: date
        outputs:
            date: ${{ steps.date.outputs.date }}

    run-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                pipeline:
                    - { name: rnaseq, url: nf-core/rnaseq, org: nf-core, rev: master, latest: true }
                    - { name: sarek, url: nf-core/sarek, org: nf-core, rev: master, latest: true }
                compute_env:
                    - TOWER_CE_AWS_CPU
                    - TOWER_CE_AZURE_CPU
                    - TOWER_CE_GCP_CPU
                include:
                    - compute_env: TOWER_CE_AWS_CPU
                      workdir: TOWER_BUCKET_AWS
                    - compute_env: TOWER_CE_AZURE_CPU
                      workdir: TOWER_BUCKET_AZURE
                    - compute_env: TOWER_CE_GCP_CPU
                      workdir: TOWER_BUCKET_GCP
        steps:
            - uses: seqeralabs/action-tower-launch@v1
              name: run.${{ matrix.pipeline.name }}.${{ matrix.compute_env }}
              with:
                pipeline: ${{ matrix.pipeline.url }}
                workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
                access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
                compute_env: ${{ secrets[matrix.compute_env] }}
                workdir: "${{ secrets[matrix.workdir] }}/work/${{ matrix.pipeline.name }}/work-${{ needs.getdate.outputs.date }}"
                run_name: "${{ matrix.pipeline }}_${{ matrix.compute_env }}"
                profiles: test
                parameters: |
                    {
                        "outdir": "${{ matrix[secrets.workdir] }}/${{ matrix.pipeline.name }}/results-test-${{ needs.getdate.outputs.date }}"
                    }

            - uses: actions/upload-artifact@v3
              with:
                name: ${{ matrix.pipeline }}_${{ matrix.compute_env }}_log
                path: tower_action_*.log

