name: Continuous tests for running the pipelines on cloud
run-name: Submit workflow for periodic testing
on: 
    workflow_dispatch:
    schedule:
    # Every Wednesday at 2am
    - cron: '0 2 * * 3'


jobs:
    getdate:
        runs-on: ubuntu-latest
        steps:
            - name: "Get current date"
              run: |
                echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
              id: date
        outputs:
            date: ${{ steps.date.outputs.date }}

    runtest:
        runs-on: ubuntu-latest
        name: ${{ matrix.pipeline.name }}.${{ matrix.compute_env }}
        needs: getdate
        continue-on-error: true
        strategy:
            matrix:
                pipeline:
                    - { name: rnaseq, url: 'https://github.com/nf-core/rnaseq', org: nf-core, rev: master, latest: true }
                    - { name: sarek, url: 'https://github.com/nf-core/sarek', org: nf-core, rev: master, latest: true }
                compute_env:
                    - TOWER_CE_AWS_CPU
                include:
                    - compute_env: TOWER_CE_AWS_CPU
                      workdir: TOWER_BUCKET_AWS
                    # To add more compute envs add both compute_env and workdir here. These should be secrets and retrieved in the same manner.
                      
        steps:
            - uses: adamrtalbot/action-tower-launch@4b50048a3bb0c57cff8a5e9b29e6035ea1f58074
              with:
                pipeline: ${{ matrix.pipeline.url }}
                workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
                access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
                compute_env: ${{ secrets[matrix.compute_env] }}
                workdir: "${{ secrets[matrix.workdir] }}/work/${{ matrix.pipeline.name }}/work-${{ needs.getdate.outputs.date }}"
                run_name: "${{ matrix.pipeline.name }}_${{ matrix.compute_env }}"
                revision: "${{ matrix.pipeline.rev }}"
                profiles: test
                wait: SUBMITTED
                parameters: |
                    {
                        "outdir": "${{ matrix[secrets.workdir] }}/${{ matrix.pipeline.name }}/results-test-${{ needs.getdate.outputs.date }}"
                    }

            - uses: actions/upload-artifact@v3
              if: success() || failure()
              with:
                name: ${{ matrix.pipeline.name }}_${{ matrix.compute_env }}_log
                path: tower_action_*.log

