name: manual-run-pipeline
run-name: manual-trigger
on:
  workflow_dispatch:
    inputs:
      pipelines:
        description: "Pipeline JSON string"
        type: string
        default: '[{"name": "hello", "url": "hello_world", "rev": "master", "latest": true, "profiles": ""}]'
      compute_envs:
        description: "Compute Environment JSON string"
        type: string
        default: '[{"name": "aws", "ref": "seqera_aws_ireland_fusionv2_nvme", "workdir": "s3://scidev-eu-west-1", "workspace_id": "162690105070735"}]'
      dryrun:
        description: "Dryrun (do not submit pipeline)"
        default: false
        type: boolean
        required: false
      timer:
        description: "Environment"
        default: delay1mins
        type: choice
        options:
          - noDelay
          - delay1mins
          - delay5mins
          - delay15mins
          - delay30mins
          - delay60mins
          - delay120mins
          - delay360mins
          - waitForReviewer
      slack:
        description: Slack hook
        type: boolean
        required: false
        default: false
      remove:
        description: Delete run
        default: true
        type: boolean
        required: false

jobs:
  autorun-pipeline:
    name: Run pipeline
    uses: ./.github/workflows/autorun.yml
    with:
      pipelines: ${{ inputs.pipelines }}
      compute_envs: ${{ inputs.compute_envs }}
      dryrun: ${{ inputs.dryrun }}
      timer: ${{ inputs.timer }}
      slack: ${{ inputs.slack }}
      remove: ${{ inputs.remove }}
    secrets: inherit
